// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkaaqqspivxlvwqnbtiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrYWFxcXNwaXZ4bHZ3cW5idGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3OTMwOTUsImV4cCI6MjA1MzM2OTA5NX0.xUwd0jwJvDvO92p39nvocp36xnCiqzL8vtC_IEB0eus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);